apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: {{ .Values.name }}
    template: {{ .Values.name }}-build-template
  name: {{ .Values.name }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:{{ .Values.build_tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  successfulBuildsHistoryLimit: 3
status:
  lastVersion: 1
