---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
  {{- if ip_whitelist }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: {{ ip_whitelist }}
  {{- end }}
spec:
  host: "{{ .Values.hostname | default (printf "%s-%s" .Values.name .Values.namespace) }}.{{ .Values.wildcard_route }}"
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: "{{ .Values.name }}"
    weight: 100
  wildcardPolicy: None
