---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: 8080-tcp
  selector:
    app: {{ .Values.app_name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
